// <auto-generated />
using LaptopService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaptopService.Migrations
{
    [DbContext(typeof(LaptopServiceContext))]
    [Migration("20241123035734_seed data to Laptop table")]
    partial class seeddatatoLaptoptable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaptopService.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Laptop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            Image = "https://mac24h.vn/images/detailed/94/XPS_9340.jpg",
                            Name = "Dell XPS 13",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Image = "https://mac24h.vn/images/detailed/94/XPS_9500.jpg",
                            Name = "Dell XPS 15",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 3,
                            Color = "Silver",
                            Image = "https://mac24h.vn/images/detailed/94/Inspiron_14.jpg",
                            Name = "Dell Inspiron 14",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Color = "Gray",
                            Image = "https://mac24h.vn/images/detailed/94/Latitude_7420.jpg",
                            Name = "Dell Latitude 7420",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            Image = "https://mac24h.vn/images/detailed/94/Precision_5550.jpg",
                            Name = "Dell Precision 5550",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 6,
                            Color = "White",
                            Image = "https://mac24h.vn/images/detailed/94/Vostro_3400.jpg",
                            Name = "Dell Vostro 3400",
                            Quantity = 18
                        },
                        new
                        {
                            Id = 7,
                            Color = "Blue",
                            Image = "https://mac24h.vn/images/detailed/94/G3_15.jpg",
                            Name = "Dell G3 15",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            Image = "https://mac24h.vn/images/detailed/94/Alienware_m15.jpg",
                            Name = "Dell Alienware m15",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 9,
                            Color = "White",
                            Image = "https://mac24h.vn/images/detailed/94/XPS_9700.jpg",
                            Name = "Dell XPS 17",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 10,
                            Color = "Silver",
                            Image = "https://mac24h.vn/images/detailed/94/Inspiron_15.jpg",
                            Name = "Dell Inspiron 15",
                            Quantity = 11
                        },
                        new
                        {
                            Id = 11,
                            Color = "Gray",
                            Image = "https://mac24h.vn/images/detailed/94/Latitude_5420.jpg",
                            Name = "Dell Latitude 5420",
                            Quantity = 13
                        },
                        new
                        {
                            Id = 12,
                            Color = "Black",
                            Image = "https://mac24h.vn/images/detailed/94/Precision_5750.jpg",
                            Name = "Dell Precision 5750",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 13,
                            Color = "White",
                            Image = "https://mac24h.vn/images/detailed/94/Vostro_3500.jpg",
                            Name = "Dell Vostro 3500",
                            Quantity = 16
                        },
                        new
                        {
                            Id = 14,
                            Color = "Blue",
                            Image = "https://mac24h.vn/images/detailed/94/G5_15.jpg",
                            Name = "Dell G5 15",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 15,
                            Color = "Black",
                            Image = "https://mac24h.vn/images/detailed/94/Alienware_m17.jpg",
                            Name = "Dell Alienware m17",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 16,
                            Color = "White",
                            Image = "https://mac24h.vn/images/detailed/94/XPS_13_Plus.jpg",
                            Name = "Dell XPS 13 Plus",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 17,
                            Color = "Silver",
                            Image = "https://mac24h.vn/images/detailed/94/Inspiron_16.jpg",
                            Name = "Dell Inspiron 16",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 18,
                            Color = "Gray",
                            Image = "https://mac24h.vn/images/detailed/94/Latitude_7320.jpg",
                            Name = "Dell Latitude 7320",
                            Quantity = 14
                        },
                        new
                        {
                            Id = 19,
                            Color = "Black",
                            Image = "https://mac24h.vn/images/detailed/94/Precision_3550.jpg",
                            Name = "Dell Precision 3550",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 20,
                            Color = "White",
                            Image = "https://mac24h.vn/images/detailed/94/Vostro_5500.jpg",
                            Name = "Dell Vostro 5500",
                            Quantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
